### PR TITLE
compatibility work for 1.9.2 - case statement & initialization value

### PR DESCRIPTION
**Pull request by tjoyal**
I probably should have make this 2 different fixes but bear with me, I'm new to github :)
- case statement compatibility with 1.9.2
- initialization of event time
# 

Still unable to make it work on 1.9.2 

undefined method `logger' for #WhoopsLogger::Configuration:0x996432c

/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/bundler/gems/whoops_logger-8365db69583f/lib/whoops_logger/sender.rb:80:in `logger'
/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/bundler/gems/whoops_logger-8365db69583f/lib/whoops_logger/sender.rb:32:in`send_message'
/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/bundler/gems/whoops_logger-8365db69583f/lib/whoops_logger.rb:32:in `send_message'
/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/bundler/gems/whoops_logger-8365db69583f/lib/whoops_logger.rb:27:in`log'

### CODE REVIEW

**Comment by flyingmachine** [comment]
This was great, thank you!

**Comment by flyingmachine** [comment]
This change is part of gem 0.1.3
